export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const EMPTY_CART = "EMPTY_CART"
export const LOGIN = "LOGIN"
export const SET_LOGIN = "SET_LOGIN"
export const LOGOUT = "LOGOUT"